### ISSUE TITLE
gltf - cannot open ( anymore ) with Blender

### ISSUE THREAD

**Issue by KammutierSpule** [cqparts/cqparts#132]
https://i.imgur.com/PthUBnv.png

Yesterday I installed cqparts via pip and it worked ok.
Today I installed via conda and I got this error.

I installed it via
$ sh Anaconda3-5.3.1-Linux-x86_64.sh
$ conda create --quiet --name testenv -c cadquery -c conda-forge freecad=0.18 python=3.6
$ source activate testenv
$ pip install cqparts

This is the project I am generating:
https://github.com/gnhdesign/ct1

and I am using this Blender addon
https://github.com/KhronosGroup/glTF-Blender-IO

**Comment by fragmuffin** [comment]
Thanks for the feedback @KammutierSpule

Looking into it from my phone for now, this is where the exception is raised `assert False` 
https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/io/com/gltf2_io.py#L52
But it's not root cause.

**Comment by KammutierSpule** [comment]
I opened a cross issue at glTF project
https://github.com/KhronosGroup/glTF-Blender-IO/issues/169#issuecomment-447560442
I didn't get a chance yet to generate a sample file for them. If you have some file to test and send to them I will appreciate.

**Comment by fragmuffin** [comment]
Yeah, I didn't have much of a chance today I'm sorry.
I'm travelling for work, I'll be back in about 3 days, and then I'll have more of a chance to reproduce this fault myself.

> I didn't get a chance yet to generate a sample file for them.

Oh! that's an easy one; essentially everything from [the examples page](https://cqparts.github.io/examples/) is displayed using gltf.

I'll post a response in the cross-issue

**Comment by KammutierSpule** [comment]
We got the answer from Julien,

> You have an accessor.count value of 708.0, but accessor.count must be an integer
> (cf specification https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessor)
> So your gltf file is not valid.
> Seems the current version of validator don't check that, I will open an issue

This may be caused by some library version differences, because as explained before, I could get it work at first when not using Anaconda.

I guess you can easily force the output to be integer only.

**Comment by julienduroure** [comment]
Hello,

For your information, answer I received from glTF-validator team:
https://github.com/KhronosGroup/glTF-Validator/issues/109

**Comment by fragmuffin** [comment]
@KammutierSpule I think the reason this problem has surfaced is due to changes in python3's arithmetic returning floats.

Out of curiosity:
- did the installation via `pip` use python 2.x?
- did the installation via `conda` use python 3.x?

**Comment by KammutierSpule** [comment]
You can see my edit on original post with the steps I did for install and run it.
Python 3.6.7

I did install cqparts via pip while in anaconda testenv ( unless I did some mistake )
cadquery        1.2.0 
cqparts         0.2.1    
pip             18.1 

I tested on two Linux machines.

**Comment by fragmuffin** [comment]
> I did install cqparts via pip while in anaconda testenv ( unless I did some mistake )

No, that looks good; installation should be simple. And if you can `import cqparts` then installation has worked.

In your original post:

> Yesterday I installed cqparts via pip and it worked ok

I was wondering if _that_ was on python 2, since you're implying that _this_ issue wasn't present in _that_ installation...
Anyway! It's not important, I think we've found the root cause 👍

Are you able to test it with the changes in #134?
I'm still traveling, so my resources are limited.

**Comment by KammutierSpule** [comment]
> > Yesterday I installed cqparts via pip and it worked ok
> 
> I was wondering if _that_ was on python 2, since you're implying that _this_ issue wasn't present in _that_ installation...

yeah sorry I wasn't clear on that.
It means that the first time I tried, it was running on the native system (ie: not anaconda) so probably it was python2.
For the new system,  I uninstalled the native pip and run it over anaconda.

**Comment by KammutierSpule** [comment]
I believe you missed one cast at:
`return int(self.idx_len / self.idx_bytelen)`
it works after that..

**Comment by fragmuffin** [comment]
@KammutierSpule good catch!
I reverted #134 in favour of #136.
In hindsight I should have waited for your green light before merging #134.

Thanks for your help @KammutierSpule ! 👍
