### ISSUE TITLE
gltf scale

### ISSUE THREAD

**Issue by KammutierSpule** [cqparts/cqparts#145]
I am importing generated gltf files in Blender 2.80
I noticed that I need to change the node scale to from 0.001 to 0.010 in order to match the expected size of the shape in Blender Unities (1=1m)

Any idea why? Is it correct?

**Comment by KammutierSpule** [comment]
sorry I was wrong. My mistake. Will close the issue.

**Comment by fragmuffin** [comment]
Oh! I'm sort of glad you're wrong, because that had me puzzled.

I'm glad you figured it out 👍
