### ISSUE TITLE
Part.OCCError: Bnd_Box is void

### ISSUE THREAD

**Issue by jan0991** [cqparts/cqparts#146]
I am using a simple script to convert .step to .gltf
```
import sys
from cqparts import Part
args = sys.argv[1:]
filename = args[0].split(".")[0]
Part.importer('step')(args[0]).exporter('gltf')(filename + '.gltf')
```
And I get:

>   File "/home/home/.local/share/virtualenvs/blueprint-z4-87zsQ/lib/python2.7/site-
> packages/cadquery/freecad_impl/shapes.py", line 966, in clean
>   r = self.wrapped.removeSplitter()

It happens just with certain files (but they are not corrupt or anything). Any ideas what can be done to avoid this error? Also, it takes 5+ min befoer I get the error (4mb file).

**Comment by fragmuffin** [comment]
Hi @jan0991,
I haven't seen this before, do you have an example `.step` file you can share so I can replicate the fault locally?

**Comment by jan0991** [comment]
Hi, here is the file: https://www.dropbox.com/s/i3luzo5jdmjx3my/CX%20-%2037%20BL.STEP?dl=0

**Comment by jan0991** [comment]
@fragmuffin any idea why this is happening? Can I somehow ignore this and continue the file conversion?
